const keywords = {
  "Au Bon Pain": ["cafe", "pastries", "coffee", "tea", "soup", "sandwich", "wrap"],
  "Breakfast Express": ["breakfast", "sandwich", "waffles", "oatmeal", "coffee"],
  "Carnegie Mellon Cafe": ["cafe", "breakfast", "wrap", "flatbread", "ice cream", "milkshakes"],
  "Chefs Table": ["gourmet", "restaurant"],
  "City Grill": ["burger", "grill", "chicken", "sandwich", "fries"],
  "Downtown Deli": ["deli", "sandwich", "gourmet", "wraps"],
  "El Fall de Oro": ["mexican", "tacos", "burrito", "quesadilla", "salad"],
  "Entropy+": ["grocery", "snacks", "baking", "breakfast", "grab-and-go"],
  "Evgefstos": ["vegetarian", "vegan", "superfood"],
  "The Exchange": ["deli", "sandwich", "salad", "soup", "grab-and-go", "coffee", "tea"],
  "Fresh Select Soup & Salad": ["soup", "salad", "all-you-can-eat"],
  "Garden Bistro": ["vegan", "sandwich", "bowl"],
  "Gingers Express": ["deli", "sandwich", "salad", "soup", "teas", "coffee", "grab-and-go"],
  "Grill'n'Greens": ["superfood", "grill", "nutrition"],
  "Heinz Cafe": ["cafe", "coffe", "grab-and-go", "snack"],
  "iNoodle": ["asian", "tea", "noodle", "rice", "ramen"],
  "La Prima Expresso": ["organic", "coffe", "pastries", "soup", "sandwich"],
  "Mac 'N Cheese": ["mac'n cheese", "vegan", "gluten"],
  "Maggie Murph Cafe": ["cafe", "coffee", "tea", "salad", "breakfast", "sushi"],
  "Nakama": ["sushi", "japanese", "rice", "noodle"],
  "Pasta Villiggio": ["pasta", "italian", "halal"],
  "The Pomegranate": ["middle east", "kosher", "falafel", "shawarma", "sandwich", "vegatarian"],
  "Ramen Bowl": ["ramen", "asian"],
  "Rice Bowl": ["asian", "halal", "rice"],
  "Rothberrg's Roaster II": ["cafe", "teas", "coffee", "healthy"],
  "Schatz Dining Room": ["all-you-can-eat", "breakfast", "dinner", "brunch", "home", "soup", "salad"],
  "Seiber Cafe": ["cafe", "soups", "salad", "entrees"],
  "Spice It Up Grill": ["burger", "sandwich"],
  "Spinning Salads": ["salad"],
  "Stephanie's": ["pastries", "nutrition", "grab-and-go", "wraps", "deli", "sandwich", "salad", "tea", "coffee"],
  "Stir Crazy": ["asian", "noodle", "stir fry"],
  "Take Comfort": ["vegetarian", "home"],
  "Tartan Express": ["asian", "rice", "soup", "noodle"],
  "Tartans Pizza": ["pizza", "sandwich", "flatbread", "pasta", "salad"],
  "Taste of India": ["indian", "masala"],
  "Tazza D'Oro": ["cafe", "coffee", "tea", "pastries", "sandwich", "dessert"],
  "The Underground": ["burger", "pasta", "soup", "salad", "breakfast", "dessert"],
  "The Zebra Lounge": ["coffee", "tea"]
}

module.exports = keywords