export const expectedLocationData = [
  {
    conceptId: 113,
    name: "AU BON PAIN AT SKIBO CAFÉ",
    shortDescription:
      "Coffee/tea, espresso, soup, sandwiches/salads, grab-n-go, yogurt parfaits, fruit, snacks",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!  For nutritional information about Au Bon Pain's menu items, please click here <a>https://www.aubonpain.com/nutrition</a> To place an Au Bon Pain catering order, please contact 1-800-765-4227 or visit http://aubonpain.com/cateringFor on-campus assistance, call 412-621-1934.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/113",
    location: "Cohon Center, Second floor",
    menu: "https://web.archive.org/web/20230806004812/https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/113/abp-menu6.pdf",
    coordinates: { lat: 40.44392022644891, lng: -79.94220130436851 },
    acceptsOnlineOrders: true,
    times: [
      {
        start: { day: 0, hour: 16, minute: 30 },
        end: { day: 0, hour: 20, minute: 0 },
      },
      {
        start: { day: 1, hour: 8, minute: 0 },
        end: { day: 1, hour: 20, minute: 0 },
      },
      {
        start: { day: 2, hour: 8, minute: 0 },
        end: { day: 2, hour: 20, minute: 0 },
      },
      {
        start: { day: 3, hour: 8, minute: 0 },
        end: { day: 3, hour: 20, minute: 0 },
      },
      {
        start: { day: 4, hour: 8, minute: 0 },
        end: { day: 4, hour: 20, minute: 0 },
      },
      {
        start: { day: 5, hour: 8, minute: 0 },
        end: { day: 5, hour: 23, minute: 59 },
      },
      {
        start: { day: 6, hour: 16, minute: 30 },
        end: { day: 6, hour: 20, minute: 0 },
      },
    ],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 184,
    name: "CIAO BELLA",
    shortDescription: "Customizable pasta plates",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/184",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.4432203633545, lng: -79.94203823851873 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 95,
    name: "DE FER COFFEE & TEA AT MAGGIE MURPH CAFÉ",
    shortDescription:
      "Locally-roasted specialty coffee, tea, and scratch-made food",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/95",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44110394047497, lng: -79.94341681666283 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 134,
    name: "E.A.T. (EVENINGS AT TEPPER) - ROHR COMMONS",
    shortDescription: "Dinner options at Tepper are Grubhub only!",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/134",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44496677039454, lng: -79.94543510284873 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 178,
    name: "THE EDGE CAFE & MARKET",
    shortDescription: "Vaad-certified kosher bagels, pizza, bourekas & more!",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/178",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44265640089745, lng: -79.94021168805847 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 88,
    name: "EGG SHOPPE - GRUBHUB ONLY",
    shortDescription:
      "Breakfast available only on Grubhub for pickup in Schatz.",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/88",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44322866937478, lng: -79.94252749706692 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 103,
    name: "ENTROPY+",
    shortDescription:
      "On-campus convenience store, serving snacks, grab-and-go meals, coffee, & more",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/103",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44294406631636, lng: -79.9421613966706 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 92,
    name: "THE EXCHANGE",
    shortDescription:
      "Deli and breakfast sandwiches, daily hot entrées, grab-and-go.",
    description:
      "The Exchange offers custom deli sandwiches, soups, hot entrées, fresh baked goods, fruit, yogurt parfaits, snack and energy bars, and other grab-and-go items. The designated coffee bar includes hot brewed La Prima coffee, specialty and organic teas, cold beverages, and bottled juices.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/92",
    location: "Posner Hall, 1st Floor",
    menu: "https://web.archive.org/web/20240721001349/https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/92/menu-exchange-2024-25-v2.pdf",
    coordinates: { lat: 40.44144439971656, lng: -79.94195512801193 },
    acceptsOnlineOrders: false,
    times: [
      {
        start: { day: 1, hour: 8, minute: 0 },
        end: { day: 1, hour: 15, minute: 0 },
      },
      {
        start: { day: 2, hour: 8, minute: 0 },
        end: { day: 2, hour: 15, minute: 0 },
      },
      {
        start: { day: 3, hour: 8, minute: 0 },
        end: { day: 3, hour: 15, minute: 0 },
      },
      {
        start: { day: 4, hour: 8, minute: 0 },
        end: { day: 4, hour: 15, minute: 0 },
      },
      {
        start: { day: 5, hour: 8, minute: 0 },
        end: { day: 5, hour: 15, minute: 0 },
      },
    ],
    todaysSpecials: [
      {
        title: "Brunch at The EXCHANGE Every Saturday",
        description:
          "Come and Enjoy our Plated Brunch with Eggs Bacon Sausages French Toast Waffles Offerings Change Every Week",
      },
    ],
    todaysSoups: [
      {
        title: "Potato and Bacon Chowder",
        description: "Crispy Bacon Green Onions and Red Bliss Potatoes",
      },
      {
        title: "Hearty Potato Bacon Chowder",
        description: "Finished with Fresh Scallions",
      },
    ],
  },
  {
    conceptId: 126,
    name: "FOOD HALL AT RESNIK",
    shortDescription: "Summer all-you-care-to-eat: OPENS JUNE 24!",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/126",
    location: "",
    menu: undefined,
    coordinates: undefined,
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 173,
    name: "FORBES AVENUE SUBS - ROHR COMMONS",
    shortDescription:
      "Made-to-order deli-style subs and wraps. Vegan options available.",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/173",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44490020783157, lng: -79.94540910407714 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 91,
    name: "EL GALLO DE ORO",
    shortDescription:
      "Mexican cuisine, burritos and burrito bowls, tacos, quesadillas, salads",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/91",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44306965961788, lng: -79.94207835253889 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 139,
    name: "GRANO PIZZA",
    shortDescription:
      "Hand-stretched, personal-sized pizzas on a New York or focaccia-style crust",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/139",
    location: "",
    menu: undefined,
    coordinates: undefined,
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 110,
    name: "HUNAN EXPRESS",
    shortDescription: "Asian cuisine, rice bowls, boba/bubble tea, smoothies",
    description:
      "Authentic Chinese cuisine, featuring sauces made with bone broth, choose your base of noodles or rice and build your own meal with General Tso’s chicken, stir fry tofu, seasonal vegetables and pork ribs in black bean sauce. Braised fish, spring rolls, pork dumplings, red bean rice cakes are available daily. Enjoy fruit smoothies and build-your-own milk or fruit boba tea, with bubble toppings like tapioca, rainbow jelly, lychee jelly and popping boba.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/110",
    location: "Newell-Simon Atrium",
    menu: "https://web.archive.org/web/20240901003526/https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/110/Fall Menus 2024 (25).pdf",
    coordinates: { lat: 40.44326419955131, lng: -79.94551330831828 },
    acceptsOnlineOrders: true,
    times: [
      {
        start: { day: 0, hour: 12, minute: 0 },
        end: { day: 0, hour: 20, minute: 0 },
      },
      {
        start: { day: 1, hour: 10, minute: 30 },
        end: { day: 1, hour: 20, minute: 0 },
      },
      {
        start: { day: 2, hour: 10, minute: 30 },
        end: { day: 2, hour: 20, minute: 0 },
      },
      {
        start: { day: 3, hour: 10, minute: 30 },
        end: { day: 3, hour: 20, minute: 0 },
      },
      {
        start: { day: 4, hour: 10, minute: 30 },
        end: { day: 4, hour: 20, minute: 0 },
      },
      {
        start: { day: 5, hour: 10, minute: 30 },
        end: { day: 5, hour: 20, minute: 0 },
      },
    ],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 115,
    name: "ROHR CAFÉ  - LA PRIMA",
    shortDescription:
      "La Prima's second location on campus serving Italian-style coffee and food",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/115",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44347617300122, lng: -79.94480928001676 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 136,
    name: "MILLIE'S COFFEE 'N' CREAMERY - ROHR COMMONS",
    shortDescription:
      "NOW OPEN! Sustainably sourced coffee, ice cream, and vegan gelato.",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/136",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44497677044086, lng: -79.94526274161514 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 127,
    name: "NOURISH",
    shortDescription:
      "Closed until fall semester: Grab and go available in Entropy",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/127",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44296, lng: -79.941815 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 94,
    name: "LA PRIMA ESPRESSO",
    shortDescription:
      "Italian-style coffee, pastries, grab-and-go sandwiches, salads, and sides",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/94",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44259053115122, lng: -79.94597744494271 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 186,
    name: "REDHAWK COFFEE",
    shortDescription:
      "Local coffee roaster serving specialty coffee, tea, baked goods, and grab-and-go food.",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/186",
    location: "",
    menu: undefined,
    coordinates: undefined,
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 174,
    name: "REVOLUTION NOODLE",
    shortDescription:
      "Customizable Malatang Noodle bowls, from the owners of Hunan Express",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/174",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44336219896886, lng: -79.94196740444092 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 108,
    name: "SCHATZ DINING ROOM",
    shortDescription: "All-you-care-to-eat residential dining hall",
    description:
      "Schatz Dining Room is piloting all-you-care-to-eat lunchtime service for all community members, including undergraduate students.Schatz Dining Room offers campus's only all-you-care-to-eat residential dining room. Schatz serves breakfast, lunch and dinner, Monday - Friday, and brunch and dinner on the weekends. Breakfast and brunch offerings include cereal, fruit, egg dishes, breakfast meats, hot griddled items like pancakes and french toast, make-your-own waffles, and an avoiding gluten breakfast station and avoiding gluten options for lunch and dinner. Lunch and dinner include five stations serving a rotating menu of hot entrees, vegan and vegetarian options, soup and salad, made-to-order sandwiches, beverages and desserts. To make a reservation, please email schatzreservations@andrew.cmu.edu",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/108",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: { lat: 40.44313373573427, lng: -79.94252833667237 },
    acceptsOnlineOrders: false,
    times: [
      {
        start: {
          day: 0,
          hour: 10,
          minute: 30,
        },
        end: {
          day: 0,
          hour: 14,
          minute: 30,
        },
      },
      {
        start: {
          day: 0,
          hour: 16,
          minute: 30,
        },
        end: {
          day: 0,
          hour: 20,
          minute: 30,
        },
      },
      {
        start: {
          day: 1,
          hour: 7,
          minute: 30,
        },
        end: {
          day: 1,
          hour: 10,
          minute: 0,
        },
      },
      {
        start: {
          day: 1,
          hour: 11,
          minute: 0,
        },
        end: {
          day: 1,
          hour: 14,
          minute: 0,
        },
      },
      {
        start: {
          day: 1,
          hour: 16,
          minute: 30,
        },
        end: {
          day: 1,
          hour: 20,
          minute: 30,
        },
      },
      {
        start: {
          day: 2,
          hour: 7,
          minute: 30,
        },
        end: {
          day: 2,
          hour: 10,
          minute: 0,
        },
      },
      {
        start: {
          day: 2,
          hour: 11,
          minute: 0,
        },
        end: {
          day: 2,
          hour: 14,
          minute: 0,
        },
      },
      {
        start: {
          day: 2,
          hour: 16,
          minute: 30,
        },
        end: {
          day: 2,
          hour: 20,
          minute: 30,
        },
      },
      {
        start: {
          day: 3,
          hour: 7,
          minute: 30,
        },
        end: {
          day: 3,
          hour: 10,
          minute: 0,
        },
      },
      {
        start: {
          day: 3,
          hour: 11,
          minute: 0,
        },
        end: {
          day: 3,
          hour: 14,
          minute: 0,
        },
      },
      {
        start: {
          day: 3,
          hour: 16,
          minute: 30,
        },
        end: {
          day: 3,
          hour: 20,
          minute: 30,
        },
      },
      {
        start: {
          day: 4,
          hour: 7,
          minute: 30,
        },
        end: {
          day: 4,
          hour: 10,
          minute: 0,
        },
      },
      {
        start: {
          day: 4,
          hour: 11,
          minute: 0,
        },
        end: {
          day: 4,
          hour: 14,
          minute: 0,
        },
      },
      {
        start: {
          day: 4,
          hour: 16,
          minute: 30,
        },
        end: {
          day: 4,
          hour: 20,
          minute: 30,
        },
      },
      {
        start: {
          day: 5,
          hour: 7,
          minute: 30,
        },
        end: {
          day: 5,
          hour: 10,
          minute: 0,
        },
      },
      {
        start: {
          day: 5,
          hour: 11,
          minute: 0,
        },
        end: {
          day: 5,
          hour: 14,
          minute: 0,
        },
      },
      {
        start: {
          day: 5,
          hour: 16,
          minute: 30,
        },
        end: {
          day: 5,
          hour: 20,
          minute: 30,
        },
      },
      {
        start: {
          day: 6,
          hour: 10,
          minute: 30,
        },
        end: {
          day: 6,
          hour: 14,
          minute: 30,
        },
      },
      {
        start: {
          day: 6,
          hour: 16,
          minute: 30,
        },
        end: {
          day: 6,
          hour: 20,
          minute: 30,
        },
      },
    ],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 180,
    name: "SCOTTY'S MARKET BY SALEM'S",
    shortDescription:
      "International and conventional groceries, savory grilled meats and hot meals.",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/180",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44414285761781, lng: -79.93888579754876 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 190,
    name: "STACK'D DESSERT BAR",
    shortDescription:
      "Cool down this summer with milkshakes, ice cream sundaes and floats!",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/190",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44541493684331, lng: -79.94298366401661 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 188,
    name: "STACK'D UNDERGROUND",
    shortDescription:
      "Smashed burgers, Nashville-style chicken an gourmet grilled cheese",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/188",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44538605085632, lng: -79.9430188095375 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 148,
    name: "STEPHANIE'S - MARKET C",
    shortDescription:
      "Fresh sandwiches, wraps and salads, snacks, sweets, gourmet coffee and cold beverages",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/148",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44618769931711, lng: -79.95093385349946 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 82,
    name: "TAHINI",
    shortDescription: "Fresh Mediterranean, Certified Kosher Cuisine",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/82",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44260716039899, lng: -79.93995513782087 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 168,
    name: "TARTAN FOOD TRUCK",
    shortDescription: "Campus food truck",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/168",
    location: "",
    menu: undefined,
    coordinates: undefined,
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 114,
    name: "TASTE OF INDIA",
    shortDescription: "Taste of India provide a vibrant tastes of India.",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/114",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44253705946464, lng: -79.9400539411368 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 185,
    name: "TEPPER TAQUERIA",
    shortDescription:
      "Mexican-style street tacos, burritos, quesadillas, bowls, and nachos",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/185",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44494190940949, lng: -79.94547335554091 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 138,
    name: "TRUE BURGER",
    shortDescription:
      "Unique, hand-crafted signature sandwiches and smash burgers",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/138",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44319390927541, lng: -79.9420529542194 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 98,
    name: "URBAN REVOLUTION - GRUBHUB ONLY",
    shortDescription: "Grubhub-only, featuring fresh-carved rotisserie options",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/98",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44245836757329, lng: -79.94002835619484 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 155,
    name: "WILD BLUE SUSHI - RUGE ATRIUM",
    shortDescription:
      "Fresh prepared sushi, hot rice bowls, bubble tea and coffee",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/155",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44269873724883, lng: -79.94664155857618 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 84,
    name: "ZEBRA LOUNGE",
    shortDescription:
      "hot and iced coffee and espresso drinks, pastries, sushi, bagels, pizza",
    description: "",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/84",
    location: "",
    menu: undefined,
    coordinates: { lat: 40.44161664158368, lng: -79.94285872206078 },
    acceptsOnlineOrders: false,
    times: [],
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
];
