import { ILocation } from "types";

export const expectedLocationData: ILocation[] = [
  {
    conceptId: 113,
    name: "AU BON PAIN AT SKIBO CAFÉ",
    shortDescription:
      "Coffee/tea, espresso, soup, sandwiches/salads, grab-n-go, yogurt parfaits, fruit, snacks",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!  For nutritional information about Au Bon Pain's menu items, please click here <a>https://www.aubonpain.com/nutrition</a> To place an Au Bon Pain catering order, please contact 1-800-765-4227 or visit http://aubonpain.com/cateringFor on-campus assistance, call 412-621-1934.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/113",
    location: "Cohon Center, Second floor",
    menu: "https://web.archive.org/web/20230806004812/https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/113/abp-menu6.pdf",
    coordinates: {
      lat: 40.44,
      lng: -79.94,
    },
    acceptsOnlineOrders: true,
    times: [
      {
        year: 2024,
        month: 8,
        day: 5,
        startMinutesFromMidnight: 990,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 8,
        day: 6,
        startMinutesFromMidnight: 990,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 8,
        day: 7,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 8,
        day: 8,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 8,
        day: 9,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 8,
        day: 10,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 8,
        day: 11,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 1439,
      },
    ],
    today: {
      year: 2024,
      month: 8,
      day: 5,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 184,
    name: "CIAO BELLA",
    shortDescription: "Customizable pasta plates",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/184",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 95,
    name: "DE FER COFFEE & TEA AT MAGGIE MURPH CAFÉ",
    shortDescription:
      "Locally-roasted specialty coffee, tea, and scratch-made food",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/95",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 134,
    name: "E.A.T. (EVENINGS AT TEPPER) - ROHR COMMONS",
    shortDescription: "Dinner options at Tepper are Grubhub only!",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/134",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 178,
    name: "THE EDGE CAFE & MARKET",
    shortDescription: "Vaad-certified kosher bagels, pizza, bourekas & more!",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/178",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 88,
    name: "EGG SHOPPE - GRUBHUB ONLY",
    shortDescription:
      "Breakfast available only on Grubhub for pickup in Schatz.",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/88",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 103,
    name: "ENTROPY+",
    shortDescription:
      "On-campus convenience store, serving snacks, grab-and-go meals, coffee, & more",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/103",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 92,
    name: "THE EXCHANGE",
    shortDescription:
      "Deli and breakfast sandwiches, daily hot entrées, grab-and-go.",
    description:
      "The Exchange offers custom deli sandwiches, soups, hot entrées, fresh baked goods, fruit, yogurt parfaits, snack and energy bars, and other grab-and-go items. The designated coffee bar includes hot brewed La Prima coffee, specialty and organic teas, cold beverages, and bottled juices.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/92",
    location: "Posner Hall, 1st Floor",
    menu: "https://web.archive.org/web/20240721001349/https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/92/menu-exchange-2024-25-v2.pdf",
    coordinates: {
      lat: 40.441354,
      lng: -79.942125,
    },
    acceptsOnlineOrders: false,
    times: [
      {
        year: 2024,
        month: 7,
        day: 22,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
      {
        year: 2024,
        month: 7,
        day: 23,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
      {
        year: 2024,
        month: 7,
        day: 24,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
      {
        year: 2024,
        month: 7,
        day: 25,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
      {
        year: 2024,
        month: 7,
        day: 26,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
    ],
    today: {
      year: 2024,
      month: 7,
      day: 20,
    },
    todaysSpecials: [
      {
        title: "Brunch at The EXCHANGE Every Saturday",
        description:
          "Come and Enjoy our Plated Brunch with Eggs Bacon Sausages French Toast Waffles Offerings Change Every Week",
      },
    ],
    todaysSoups: [
      {
        title: "Potato and Bacon Chowder",
        description: "Crispy Bacon Green Onions and Red Bliss Potatoes",
      },
      {
        title: "Hearty Potato Bacon Chowder",
        description: "Finished with Fresh Scallions",
      },
    ],
  },
  {
    conceptId: 126,
    name: "FOOD HALL AT RESNIK",
    shortDescription: "Summer all-you-care-to-eat: OPENS JUNE 24!",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/126",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 173,
    name: "FORBES AVENUE SUBS - ROHR COMMONS",
    shortDescription:
      "Made-to-order deli-style subs and wraps. Vegan options available.",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/173",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 91,
    name: "EL GALLO DE ORO",
    shortDescription:
      "Mexican cuisine, burritos and burrito bowls, tacos, quesadillas, salads",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/91",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 139,
    name: "GRANO PIZZA",
    shortDescription:
      "Hand-stretched, personal-sized pizzas on a New York or focaccia-style crust",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/139",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 110,
    name: "HUNAN EXPRESS",
    shortDescription: "Asian cuisine, rice bowls, boba/bubble tea, smoothies",
    description:
      "Authentic Chinese cuisine, featuring sauces made with bone broth, choose your base of noodles or rice and build your own meal with General Tso’s chicken, stir fry tofu, seasonal vegetables and pork ribs in black bean sauce. Braised fish, spring rolls, pork dumplings, red bean rice cakes are available daily. Enjoy fruit smoothies and build-your-own milk or fruit boba tea, with bubble toppings like tapioca, rainbow jelly, lychee jelly and popping boba.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/110",
    location: "Newell-Simon Atrium",
    menu: "https://web.archive.org/web/20240901003526/https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/110/Fall Menus 2024 (25).pdf",
    coordinates: {
      lat: 40.4433922,
      lng: -79.9455957,
    },
    acceptsOnlineOrders: true,
    times: [
      {
        year: 2024,
        month: 9,
        day: 1,
        startMinutesFromMidnight: 720,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 9,
        day: 2,
        startMinutesFromMidnight: 630,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 9,
        day: 3,
        startMinutesFromMidnight: 630,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 9,
        day: 4,
        startMinutesFromMidnight: 630,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 9,
        day: 5,
        startMinutesFromMidnight: 630,
        endMinutesFromMidnight: 1200,
      },
      {
        year: 2024,
        month: 9,
        day: 6,
        startMinutesFromMidnight: 630,
        endMinutesFromMidnight: 1200,
      },
    ],
    today: {
      year: 2024,
      month: 8,
      day: 31,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 115,
    name: "ROHR CAFÉ  - LA PRIMA",
    shortDescription:
      "La Prima's second location on campus serving Italian-style coffee and food",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/115",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 136,
    name: "MILLIE'S COFFEE 'N' CREAMERY - ROHR COMMONS",
    shortDescription:
      "NOW OPEN! Sustainably sourced coffee, ice cream, and vegan gelato.",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/136",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 127,
    name: "NOURISH",
    shortDescription:
      "Closed until fall semester: Grab and go available in Entropy",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/127",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 94,
    name: "LA PRIMA ESPRESSO",
    shortDescription:
      "Italian-style coffee, pastries, grab-and-go sandwiches, salads, and sides",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/94",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 186,
    name: "REDHAWK COFFEE",
    shortDescription:
      "Local coffee roaster serving specialty coffee, tea, baked goods, and grab-and-go food.",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/186",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 174,
    name: "REVOLUTION NOODLE",
    shortDescription:
      "Customizable Malatang Noodle bowls, from the owners of Hunan Express",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/174",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 108,
    name: "SCHATZ DINING ROOM",
    shortDescription: "All-you-care-to-eat residential dining hall",
    description:
      "Schatz Dining Room is piloting all-you-care-to-eat lunchtime service for all community members, including undergraduate students.Schatz Dining Room offers campus's only all-you-care-to-eat residential dining room. Schatz serves breakfast, lunch and dinner, Monday - Friday, and brunch and dinner on the weekends. Breakfast and brunch offerings include cereal, fruit, egg dishes, breakfast meats, hot griddled items like pancakes and french toast, make-your-own waffles, and an avoiding gluten breakfast station and avoiding gluten options for lunch and dinner. Lunch and dinner include five stations serving a rotating menu of hot entrees, vegan and vegetarian options, soup and salad, made-to-order sandwiches, beverages and desserts. To make a reservation, please email schatzreservations@andrew.cmu.edu",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/108",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.4429602,
      lng: -79.9418151,
    },
    acceptsOnlineOrders: false,
    times: [
      {
        year: 2024,
        month: 9,
        day: 20,
        startMinutesFromMidnight: 450,
        endMinutesFromMidnight: 600,
      },
      {
        year: 2024,
        month: 9,
        day: 20,
        startMinutesFromMidnight: 660,
        endMinutesFromMidnight: 840,
      },
      {
        year: 2024,
        month: 9,
        day: 20,
        startMinutesFromMidnight: 990,
        endMinutesFromMidnight: 1230,
      },
      {
        year: 2024,
        month: 9,
        day: 21,
        startMinutesFromMidnight: 630,
        endMinutesFromMidnight: 870,
      },
      {
        year: 2024,
        month: 9,
        day: 21,
        startMinutesFromMidnight: 990,
        endMinutesFromMidnight: 1230,
      },
      {
        year: 2024,
        month: 9,
        day: 22,
        startMinutesFromMidnight: 630,
        endMinutesFromMidnight: 870,
      },
      {
        year: 2024,
        month: 9,
        day: 22,
        startMinutesFromMidnight: 990,
        endMinutesFromMidnight: 1230,
      },
      {
        year: 2024,
        month: 9,
        day: 23,
        startMinutesFromMidnight: 450,
        endMinutesFromMidnight: 600,
      },
      {
        year: 2024,
        month: 9,
        day: 23,
        startMinutesFromMidnight: 660,
        endMinutesFromMidnight: 840,
      },
      {
        year: 2024,
        month: 9,
        day: 23,
        startMinutesFromMidnight: 990,
        endMinutesFromMidnight: 1230,
      },
      {
        year: 2024,
        month: 9,
        day: 24,
        startMinutesFromMidnight: 450,
        endMinutesFromMidnight: 600,
      },
      {
        year: 2024,
        month: 9,
        day: 24,
        startMinutesFromMidnight: 660,
        endMinutesFromMidnight: 840,
      },
      {
        year: 2024,
        month: 9,
        day: 24,
        startMinutesFromMidnight: 990,
        endMinutesFromMidnight: 1230,
      },
      {
        year: 2024,
        month: 9,
        day: 25,
        startMinutesFromMidnight: 450,
        endMinutesFromMidnight: 600,
      },
      {
        year: 2024,
        month: 9,
        day: 25,
        startMinutesFromMidnight: 660,
        endMinutesFromMidnight: 840,
      },
      {
        year: 2024,
        month: 9,
        day: 25,
        startMinutesFromMidnight: 990,
        endMinutesFromMidnight: 1230,
      },
      {
        year: 2024,
        month: 9,
        day: 26,
        startMinutesFromMidnight: 450,
        endMinutesFromMidnight: 600,
      },
      {
        year: 2024,
        month: 9,
        day: 26,
        startMinutesFromMidnight: 660,
        endMinutesFromMidnight: 840,
      },
      {
        year: 2024,
        month: 9,
        day: 26,
        startMinutesFromMidnight: 990,
        endMinutesFromMidnight: 1230,
      },
    ],
    today: {
      year: 2024,
      month: 9,
      day: 20,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 180,
    name: "SCOTTY'S MARKET BY SALEM'S",
    shortDescription:
      "International and conventional groceries, savory grilled meats and hot meals.",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/180",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 190,
    name: "STACK'D DESSERT BAR",
    shortDescription:
      "Cool down this summer with milkshakes, ice cream sundaes and floats!",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/190",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 188,
    name: "STACK'D UNDERGROUND",
    shortDescription:
      "Smashed burgers, Nashville-style chicken an gourmet grilled cheese",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/188",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 148,
    name: "STEPHANIE'S - MARKET C",
    shortDescription:
      "Fresh sandwiches, wraps and salads, snacks, sweets, gourmet coffee and cold beverages",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/148",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 82,
    name: "TAHINI",
    shortDescription: "Fresh Mediterranean, Certified Kosher Cuisine",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/82",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 168,
    name: "TARTAN FOOD TRUCK",
    shortDescription: "Campus food truck",
    description:
      "The Exchange offers custom deli sandwiches, soups, hot entrées, fresh baked goods, fruit, yogurt parfaits, snack and energy bars, and other grab-and-go items. The designated coffee bar includes hot brewed La Prima coffee, specialty and organic teas, cold beverages, and bottled juices.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/168",
    location: "Posner Hall, 1st Floor",
    menu: "https://web.archive.org/web/20240721001349/https://apps.studentaffairs.cmu.edu/dining/dashboard_images/Production/menus/92/menu-exchange-2024-25-v2.pdf",
    coordinates: {
      lat: 401.441354,
      lng: -791.942125,
    },
    acceptsOnlineOrders: false,
    times: [
      {
        year: 2024,
        month: 7,
        day: 22,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
      {
        year: 2024,
        month: 7,
        day: 23,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
      {
        year: 2024,
        month: 7,
        day: 24,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
      {
        year: 2024,
        month: 7,
        day: 25,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
      {
        year: 2024,
        month: 7,
        day: 26,
        startMinutesFromMidnight: 480,
        endMinutesFromMidnight: 900,
      },
    ],
    today: {
      year: 2024,
      month: 7,
      day: 20,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 114,
    name: "TASTE OF INDIA",
    shortDescription: "Taste of India provide a vibrant tastes of India.",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/114",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 185,
    name: "TEPPER TAQUERIA",
    shortDescription:
      "Mexican-style street tacos, burritos, quesadillas, bowls, and nachos",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/185",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 138,
    name: "TRUE BURGER",
    shortDescription:
      "Unique, hand-crafted signature sandwiches and smash burgers",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/138",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 98,
    name: "URBAN REVOLUTION - GRUBHUB ONLY",
    shortDescription: "Grubhub-only, featuring fresh-carved rotisserie options",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/98",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 155,
    name: "WILD BLUE SUSHI - RUGE ATRIUM",
    shortDescription:
      "Fresh prepared sushi, hot rice bowls, bubble tea and coffee",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/155",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
  {
    conceptId: 84,
    name: "ZEBRA LOUNGE",
    shortDescription:
      "hot and iced coffee and espresso drinks, pastries, sushi, bagels, pizza",
    description:
      "At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try ... healthy choices, comfort food, indulgent treats … try them all!\n                                            \n                                        \n                                            Nutritional information can be found at aubonpain.com/nutrition\n                                            .\n                                        \n                                            \n                                        \n                                            To place a catering order online, visit catering.aubonpain.com\n                                            . To pay with a department or organization’s oracle string, please email your order to  abpcmu@grcafes.com\n                                            . For on-campus assistance, call 412-268-1054.",
    url: "https://apps.studentaffairs.cmu.edu/dining/conceptinfo/Concept/84",
    location: "Cohon Center, Second floor",
    menu: undefined,
    coordinates: {
      lat: 40.44401,
      lng: -79.942258,
    },
    acceptsOnlineOrders: true,
    times: [],
    today: {
      year: 2024,
      month: 11,
      day: 13,
    },
    todaysSpecials: undefined,
    todaysSoups: undefined,
  },
];

export const expectedLocationData2: ILocation[] = expectedLocationData.filter(
  (location) =>
    ["92", "110", "113", "175", "108", "168"].includes(
      location.conceptId.toString()
    )
);
